export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';

export const ADD_CARTITEM = 'ADD_CARTITEM';

export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';

export const REMOVE_CARTITEM = 'REMOVE_CARTITEM';